# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
# from spacy
language: en

pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer # use pretrained work embeddings from Glove
  - name: RegexFeaturizer # default configs
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier  # dual intent entity transformer (use for intent classification and entity extraction)
    epochs: 100
  - name: EntitySynonymMapper # mapping if things are synonyms
  - name: ResponseSelector  # dictionary with key as intent and value as predicted response template
    epochs: 100
    retrieval_intent: faq
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat
  - name: FallbackClassifier  # this classifier jandles message with low NLU confidence
    threshold: 0.5
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    random_seed: 42
  - name: RulePolicy  # add this to use forms (to collect information) with RASA open source

# TED policy --> transformer embedding dialogue policy in the paper
# memorization policy --> remembers stories from training data, and check if the current conversation matches a max_history
# in training data.
